config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  get 'movies/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies, only: %i[show]
  resources :lists, only: %i[index show create] do
    resources :bookmarks, only: %i[create]
  end
  resources :bookmarks, only: [:destroy]

  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id, message: 'is already in list'}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other, notice: 'Bookmark successfully deleted'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h1>Add a bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit, class: 'btn btn-primary mt-3' %>
  <% end %>
  <%= link_to "Go to #{@list.name}", list_path(@list), class: 'btn btn-secondary mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container-fluid banner">
  <h1>Save your favourite movies</h1>
</div>
<div class="container mt-3">
  <h2>My lists</h2>
  <hr>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-3">
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="card" style="width: 300px">
            <div class="card-body" style="text-align: center; padding: 50px; background-image: url('<%= cl_image_path list.photo.key, width: 300 %>')">
              <h5 class="card-title" style="color: white"><%= list.name %></h5>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <hr>
</div>
<div class="container  mt-3">
  <h2>Create a new list</h2>
  <div class="card">
    <div class="card-body">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create new list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-primary"  %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container mt-3">
  <h1><%= @list.name %></h1>
  <hr>
  <div class="card">
    <div class="card-body">
    <h2>Add a bookmark</h2>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment, class: "form-control" %>
        <%= f.association :movie %>
        <%= f.button :submit, {class: 'btn btn-primary mt-3'}%>
      <% end %>
    </div>
  </div>
  <hr>
  <h2>Bookmarks</h2>
  <div class="alert alert-success" role="alert">
    <% if notice.present? %>
      <%= notice %>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4">
        <div class="card">
          <%= image_tag "#{bookmark.movie.poster_url}", {class: "card-img-top"} %>
          <div class="card-body">
            <p class="card-text" >Comments: <%= bookmark.comment %></p>
            <h5 class="card-title"><%= bookmark.movie.title %></h5>
            <span>Ratings: <%= bookmark.movie.rating.to_f %><i class="fa-solid fa-star"></i></span>
            <p class="card-text"><%= bookmark.movie.overview %></p>
            <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container col-6">
  <div class="card">
    <%= image_tag "#{@movie.poster_url}", {class: "card-img-top"} %>
    <div class="card-body">
      <h4 class="card-title"><%= @movie.title %></h4>
      <p class="card-text" ><%= @movie.overview %></p>
    </div>
  </div>
</div>